dist: xenial
git:
  quiet: true
  depth: 1
notifications:
  email: false
env:
  global:
    - TERM=dumb
language: java
jdk: openjdk8
node_js: lts/*
python: 3
service:
  - docker
addons:
  apt:
    update: true
    packages:
      - sudo
      - lsof
      - wget
      - bash
      - curl
      - jq
      - libxml2-utils
      - unzip
      - docker-ce
      - python3-dev
      - python3-pip
      - python3-six
      - python3-setuptools
install: true
before_install:
  ## gradle
  #- curl -s "https://get.sdkman.io" | bash
  #- source "$HOME/.sdkman/bin/sdkman-init.sh"
  #- sed -i -e 's/^sdkman_auto_answer=false$/sdkman_auto_answer=true/g' "$HOME/.sdkman/etc/config"
  #- sdk use gradle 5.5-rc-2
  #- source "$HOME/.sdkman/bin/sdkman-init.sh"
  #@
  - docker-compose -v
  - export PATH=$HOME/.local/bin:$PATH
  - pip3 install --user $(whoami) --upgrade pip >/dev/null # pip3 -> pip
  - pip install --user $(whoami) --upgrade docker-compose httpie >/dev/null 2>&1
  - http --version --debug
  - docker-compose -v
  #
  - source <(curl -fsSL https://raw.github.com/daggerok/bash-functions/master/main.bash)
  - stop_any 5432 5672 15672 27017 8080 8000 8081 80 80

cache:
  pip: true
  packages: true
  directories:
    - $HOME/.m2
    - $HOME/.docker

jobs:
  include:

    - stage: test
      name: test
      script:
        - docker run --rm -i --name rabbitmq -p 5672:5672 rabbitmq:3.7.15-management-alpine &
        - cd $TRAVIS_BUILD_DIR/ && ./mvnw >/dev/null
        - java -jar $TRAVIS_BUILD_DIR/target/*-SNAPSHOT.jar &
        - wait_for 8080
        - http :8080 string=1
        - sleep 1s
        - http :8080 string=2
        - sleep 1s
        - http :8080 string=0
        - sleep 1s
        - stop_any 80 8080
        - docker rm -f -v rabbitmq
